name: Build HEPdata submission maker docker image

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: benjlevesque/short-sha@v1.2
      id: short-sha
    - name: Build HEPdata submission maker docker image
      run: docker build . --file Dockerfile --tag hepdata_submission_docker:${{ steps.short-sha.outputs.sha }}
